services:
  # ✅ Postgres pour stocker tes données crypto
  postgres_crypto:
    image: postgres:15
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_password
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_crypto_data:/var/lib/postgresql/data

  # ✅ Postgres interne pour Airflow (metadata: dags, tasks, etc.)
  postgres_airflow:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data

  # ✅ Airflow webserver
  airflow_webserver:
    image: apache/airflow:2.8.4
    container_name: airflow_webserver
    depends_on:
      - postgres_airflow
    env_file:
      - .env.docker
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    ports:
      - "8080:8080"
    command: webserver

  # ✅ Airflow scheduler (exécute les tâches)
  airflow_scheduler:
    image: apache/airflow:2.8.4
    container_name: airflow_scheduler
    depends_on:
      - airflow_webserver
    env_file:
      - .env.docker
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    command: scheduler



  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

# kafka
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper
    
# interface pour visualiser les topics et messages kafka
  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    depends_on:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - "8081:8080"


volumes:
  postgres_crypto_data:
  postgres_airflow_data: